[telegram]
# Get your API ID/HASH from 24397690

phone_number="+91 7979735590"
api_id=28060548
api_hash="293ceb037713515e11538a70df49e1aa"

[sending]
# The send interval is how long you want to wait between sending messages.
# The loop interval is how long you want to wait before re-sending messages to all the groups.

send_interval=0
loop_interval=0
